CREATE TABLE IF NOT EXISTS `user_role` (
	role_id INT NOT NULL AUTO_INCREMENT,
	role_name VARCHAR(64) NOT NULL,
	PRIMARY KEY (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色表' AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `user` (
	user_id INT NOT NULL AUTO_INCREMENT,
	user_name VARCHAR(64) NOT NULL,
	user_pwd VARCHAR(64) NOT NULL,
	user_contact VARCHAR(20) NOT NULL,
	user_email VARCHAR(64),
	user_create_time DATETIME NOT NULL,
	role_id INT NOT NULL,
	PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表' AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `account` (
	account_id INT NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	balance INT,
	allow_download TINYINT DEFAULT 0,
	allow_download_time DATETIME, 
	PRIMARY KEY (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='账户表' AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `goods_type` (
	type_id SMALLINT NOT NULL AUTO_INCREMENT,
	type_name VARCHAR(64) NOT NULL, 
	PRIMARY KEY(type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品分类表' AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `goods` (
	oid INT NOT NULL AUTO_INCREMENT,
	goods_uid INT NOT NULL,
	goods_name VARCHAR(64) NOT NULL,
	goods_description VARCHAR(200),
	goods_type_id SMALLINT NOT NULL,
	goods_value INT NOT NULL, 
	PRIMARY KEY(oid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品表' AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `user_favourite`(
	user_id INT NOT NULL,
	goods_id INT NOT NULL,
	favourite_time DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='我的收藏表' AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `order` (
	order_id INT NOT NULL AUTO_INCREMENT,
	account_id INT NOT NULL,
	cost INT,
	goods_id INT NOT NULL,
	order_create_time DATETIME NOT NULL,
	PRIMARY KEY(order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表' AUTO_INCREMENT=1;