const mapping = {
  'softDecoration': '软装库',
  'sofa': '沙发',
  'bed': '床具',
  'chair': '椅子',
  'cabinet': '柜具',
  'desk': '桌几',
  'light': '灯具',
  'furnishing': '陈设用品',
  'plant': '植物花草',
  'Hardware': '五金/厨卫',
  'people': '人物/器材',
  'scenario': '场景库',
  'hotel': '酒店空间',
  'home': '家装空间',
  'business': '商业空间',
  'office': '办公空间',
  'public': '公共空间',
  'outdoor': '户外建筑',
  'material': '素材库',
  'picture': '贴图分类',
  'VR': 'VR材质',
  'opticalNetwork': '光域网',
  'others': '其它',
  'software': '软件库',
  'Autodesk': 'Autodesk',
  'Adobe': 'Adobe',
  'render': '渲染器',
  'plugin': '插件',
  'tutorial': '教程库',
  '3D': '3D教程',
  '2D': '2D教程',
  'painting': '插画手绘',
  'graphic': '平面设计',
  'camera': '摄影摄像',
  'audio': '音频编辑',
};

export default {
  mapping
};
